### ISSUE TITLE
[bug] Performance on mobile devices is aaaah

### ISSUE THREAD

**Issue by rugk** [olivvybee/imagenerator#34]
**Describe the bug**
Many complex generators are so sloe, that your entered text gets delayed and you hardly can write anything.

**How it happened**
E.g. chose https://imagenerator.net/interrupting-crow and open it on mobile and write a lot of text. When editing the third input field it gets verrry laggy.

Especially when pressing the back key and you accidentally delete too much because of such a high delay it gets very annoying.

**Expected behavior**
I guess it does generate an image in each keypress/input, which is a lot of calculation power on low-end/less powerful devices.

IMHO a solution would be to throttle the generation. Lodash e.g. has a library for throttling.

**Screenshots**
N/A

**Your device information**
 - fairphone 4
 - Firefox for android version 115.2.1

**More info**
Given mobile devices are often used for sharing memes like that this can be paramound and destroy the whole ux and thus de-encentivce you from using this software that is apart from that so great.

**Comment by theresnotime** [comment]
Works fine on my phone (see attached) — sure it's not just _your_ phone?![Interrupting crow(1).png](https://github.com/olivvybee/imagenerator/assets/375162/e3414a7f-ac5c-4036-9d7f-4da25d9340e9)

**Comment by rugk** [comment]
Okay tried reproducing it again also with Chromium on the same phone. With Chromium it is way better and generally, there is one thing that really triggers it: Holding the backspace key, i.e. deleting a lot of characters (like when you want to remove a statement). 

Given there are browser differences I could go and report it to https://webcompat.com/, but maybe they'll also just say "yeah you should use throttle/debounce" hmm?

**Comment by rugk** [comment]
Works much better now!
